name: Bot Trading Automatico

on:
  schedule:
    # Se ejecuta automáticamente al minuto 0 de cada hora
    - cron: '0 * * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub cuando quieras

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar Código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar Librerías
      run: |
        pip install ccxt pandas numpy

    - name: Ejecutar Bot
      run: python bot_github.py

    # - name: Guardar Cambios del Estado en GitHub
    #   run: |
    #     git config --global user.name "GitHub Action Bot"
    #     git config --global user.email "bot@github.com"
    #     git add estado_bot.json
    #     git commit -m "Auto-update estado bot" || exit 0
    #     git push
        
    - name: Guardar Cambios del Estado e Historial en GitHub
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "bot@github.com"
        git add estado_bot.json historial_trades.csv
        git commit -m "Auto-update estado e historial bot" || exit 0
        git push
